name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t swatigoel02/custom-docker-img-1 .

      - name: Run Docker container
        run: docker run -d -p 8000:8000 swatigoel02/custom-docker-img-1
